In [1]:
infile = '/Users/benedettatorsi/Documents/Machine_Learning/ML_tutorial/values1.txt'

In [119]:
infile_events = '/Users/benedettatorsi/Documents/Machine_Learning/ML_tutorial/events1.txt'

In [118]:
def file_len(fname):
    with open(fname) as f:
        for i, l in enumerate(f):
            pass
    return i + 1

In [177]:
#checking number of events in file with event_no's and tokens
file_len(infile_events)

53

In [176]:
#obtaining a dataframe from file with factuality values
import pandas as pd

df = pd.read_csv(infile, sep='\|', header=None).dropna(axis=1)

/Users/benedettatorsi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.

In [11]:
print(df)

                             0   3      6       9        12       15  \
0   'ABC19980108.1830.0711.tml'   1   'f1'    'e1'  'ei375'     's0'
1   'ABC19980108.1830.0711.tml'   1   'f2'  'e369'  'ei431'     's0'
2   'ABC19980108.1830.0711.tml'   2   'f3'    'e3'  'ei377'     's0'
3   'ABC19980108.1830.0711.tml'   2   'f4'    'e4'  'ei378'     's0'
4   'ABC19980108.1830.0711.tml'   3   'f5'    'e7'  'ei379'     's0'
5   'ABC19980108.1830.0711.tml'   4   'f6'    'e9'  'ei380'     's0'
6   'ABC19980108.1830.0711.tml'   5   'f7'   'e10'  'ei381'     's0'
7   'ABC19980108.1830.0711.tml'   7   'f8'  'e147'  'ei382'     's0'
8   'ABC19980108.1830.0711.tml'   8   'f9'   'e11'  'ei384'     's0'
9   'ABC19980108.1830.0711.tml'   8  'f10'  'e153'  'ei383'     's0'
10  'ABC19980108.1830.0711.tml'   8  'f11'  'e376'  'ei438'  's1_s0'
11  'ABC19980108.1830.0711.tml'   8  'f12'  'e376'  'ei438'     's0'
12  'ABC19980108.1830.0711.tml'  10  'f13'   'e12'  'ei386'     's0'
13  'ABC19980108.1830.0711.tml'  10  'f14'   'e14'  'ei387'     's0'
14  'ABC19980108.1830.0711.tml'  11  'f15'   'e16'  'ei388'     's0'
15  'ABC19980108.1830.0711.tml'  11  'f16'   'e17'  'ei389'     's0'
16  'ABC19980108.1830.0711.tml'  11  'f17'   'e18'  'ei390'  's3_s0'
17  'ABC19980108.1830.0711.tml'  11  'f18'   'e18'  'ei390'     's0'
18  'ABC19980108.1830.0711.tml'  12  'f19'   'e19'  'ei391'     's0'
19  'ABC19980108.1830.0711.tml'  12  'f20'   'e20'  'ei392'     's0'
20  'ABC19980108.1830.0711.tml'  12  'f21'   'e21'  'ei393'  's4_s0'
21  'ABC19980108.1830.0711.tml'  12  'f22'   'e21'  'ei393'     's0'
22  'ABC19980108.1830.0711.tml'  14  'f23'   'e26'  'ei395'     's0'
23  'ABC19980108.1830.0711.tml'  14  'f24'   'e27'  'ei396'     's0'
24  'ABC19980108.1830.0711.tml'  14  'f25'   'e28'  'ei397'     's0'
25  'ABC19980108.1830.0711.tml'  15  'f26'   'e30'  'ei398'     's0'
26  'ABC19980108.1830.0711.tml'  16  'f27'   'e32'  'ei399'     's0'
27  'ABC19980108.1830.0711.tml'  17  'f28'   'e33'  'ei400'     's0'
28  'ABC19980108.1830.0711.tml'  18  'f29'   'e34'  'ei401'     's0'
29  'ABC19980108.1830.0711.tml'  19  'f30'   'e37'  'ei402'     's0'
30  'ABC19980108.1830.0711.tml'  19  'f31'   'e88'  'ei403'  's5_s0'
31  'ABC19980108.1830.0711.tml'  19  'f32'   'e88'  'ei403'     's0'
32  'ABC19980108.1830.0711.tml'  19  'f33'   'e91'  'ei404'  's5_s0'
33  'ABC19980108.1830.0711.tml'  19  'f34'   'e91'  'ei404'     's0'
34  'ABC19980108.1830.0711.tml'  20  'f35'   'e39'  'ei405'     's0'
35  'ABC19980108.1830.0711.tml'  20  'f36'   'e40'  'ei406'  's6_s0'
36  'ABC19980108.1830.0711.tml'  20  'f37'   'e40'  'ei406'     's0'
37  'ABC19980108.1830.0711.tml'  21  'f38'   'e41'  'ei407'     's0'
38  'ABC19980108.1830.0711.tml'  23  'f39'   'e42'  'ei408'     's0'
39  'ABC19980108.1830.0711.tml'  23  'f40'   'e43'  'ei409'     's0'
40  'ABC19980108.1830.0711.tml'  23  'f41'   'e44'  'ei410'     's0'
41  'ABC19980108.1830.0711.tml'  23  'f42'   'e46'  'ei412'     's0'
42  'ABC19980108.1830.0711.tml'  24  'f43'  'e371'  'ei433'     's0'
43  'ABC19980108.1830.0711.tml'  25  'f44'   'e48'  'ei414'     's0'
44  'ABC19980108.1830.0711.tml'  25  'f45'   'e50'  'ei415'     's0'
45  'ABC19980108.1830.0711.tml'  28  'f46'  'e375'  'ei437'     's0'
46  'ABC19980108.1830.0711.tml'  29  'f47'   'e52'  'ei417'     's0'
47  'ABC19980108.1830.0711.tml'  29  'f48'   'e53'  'ei418'     's0'
48  'ABC19980108.1830.0711.tml'  29  'f49'   'e54'  'ei419'     's0'
49  'ABC19980108.1830.0711.tml'  30  'f50'  'e374'  'ei436'  's8=s0'
50  'ABC19980108.1830.0711.tml'  30  'f51'   'e55'  'ei420'     's0'
51  'ABC19980108.1830.0711.tml'  30  'f52'   'e56'  'ei422'     's0'
52  'ABC19980108.1830.0711.tml'  30  'f53'   'e59'  'ei424'  's9=s0'
53  'ABC19980108.1830.0711.tml'  31  'f54'   'e60'  'ei425'     's0'
54  'ABC19980108.1830.0711.tml'  31  'f55'   'e64'  'ei426'     's0'
55  'ABC19980108.1830.0711.tml'  32  'f56'  'e368'  'ei430'     's0'
56  'ABC19980108.1830.0711.tml'  32  'f57'   'e65'  'ei427'     's0'
57  'ABC19980108.1830.0711.tml'  32  'f58'   'e66'  'ei428'     's0'
58  'ABC19980108.1830.0711.tml'  32  'f59'   'e67'  'ei429'     's0'

                18                21     24
0        'turning'          'AUTHOR'  'CT+'
1            'bad'          'AUTHOR'  'CT+'
2     'assistance'          'AUTHOR'  'CT+'
3        'helping'          'AUTHOR'  'CT-'
4         'fallen'          'AUTHOR'  'CT+'
5           'lost'          'AUTHOR'  'CT+'
6            'hit'          'AUTHOR'  'CT+'
7           'drop'          'AUTHOR'  'CT+'
8        'thought'          'AUTHOR'  'CT+'
9       'problems'          'AUTHOR'  'CT+'
10    'invincible'  'experts_AUTHOR'  'CT+'
11    'invincible'          'AUTHOR'   'Uu'
12      'takeover'          'AUTHOR'  'CT+'
13          'news'          'AUTHOR'  'CT+'
14         'spent'          'AUTHOR'  'CT+'
15       'thought'          'AUTHOR'  'CT+'
16          'deal'       'he_AUTHOR'  'CT+'
17          'deal'          'AUTHOR'   'Uu'
18          'sold'          'AUTHOR'  'CT+'
19          'said'          'AUTHOR'  'CT+'
20        'double'       'He_AUTHOR'  'CT+'
21        'double'          'AUTHOR'   'Uu'
22  'construction'          'AUTHOR'  'CT+'
23           'way'          'AUTHOR'  'CT+'
24        'backed'          'AUTHOR'  'CT+'
25         'break'          'AUTHOR'  'PR-'
26       'crashed'          'AUTHOR'  'CT+'
27          'owns'          'AUTHOR'  'CT+'
28          'find'          'AUTHOR'  'CT-'
29     'estimates'          'AUTHOR'  'CT+'
30         'worth'      'She_AUTHOR'  'CT+'
31         'worth'          'AUTHOR'  'CT+'
32         'worth'      'She_AUTHOR'  'PR+'
33         'worth'          'AUTHOR'   'Uu'
34       'believe'          'AUTHOR'  'CT+'
35         'going'     'They_AUTHOR'  'CT+'
36         'going'          'AUTHOR'   'Uu'
37       'believe'          'AUTHOR'  'CT-'
38       'plunged'          'AUTHOR'  'CT+'
39        'soared'          'AUTHOR'  'CT+'
40      'downturn'          'AUTHOR'  'CT+'
41      'spending'          'AUTHOR'  'CT-'
42        'thirty'          'AUTHOR'  'CT+'
43           'get'          'AUTHOR'   'Uu'
44     'discounts'          'AUTHOR'   'Uu'
45           'few'          'AUTHOR'  'CT+'
46          'boom'          'AUTHOR'  'CT+'
47       'talking'          'AUTHOR'  'CT+'
48       'layoffs'          'AUTHOR'  'PS+'
49        'gloomy'        'I=AUTHOR'  'PR+'
50         'think'          'AUTHOR'  'CT+'
51         'think'          'AUTHOR'  'CT+'
52        'change'        'I=AUTHOR'  'PR-'
53          'time'          'AUTHOR'  'CT+'
54    'reposition'          'AUTHOR'   'Uu'
55     'recession'          'AUTHOR'  'CT+'
56          'hold'          'AUTHOR'   'Uu'
57           'get'          'AUTHOR'   'Uu'
58          'goes'          'AUTHOR'  'CT+'

In [29]:
df.columns = ["article", 'sent_id', "f_id", "event_no", "ei_id", "source", 'token', 's_name', 'f_value'] #Sets headings
df["token"] = df["token"].str.replace("'", "") #This removes the apostrophes so that the tokens can match
df["f_id"] = df["f_id"].str.replace("'", "") #This removes the apostrophes so that the tokens can match
df["event_no"] = df["event_no"].str.replace("'", "") #This removes the apostrophes so that the tokens can match
df["f_value"] = df["f_value"].str.replace("'", "") #This removes the apostrophes so that the tokens can match

In [30]:
modified_df = df.drop(['article','ei_id', 'source', 's_name'], 1) #Drops unwanted columns

In [178]:
#experimenting with dataframe, you can ignore this
df2=modified_df.set_index("event_no")

In [180]:
#trying one strategy where I construct a nested dictionary with the information I need, YOU CAN IGNORE THIS
##PLAN
#dictionary = {f17: {e18: ct+}
#{f18: {e18: uu}

#in dictionary
#if key within key is the same, if key is smaller than other key then get the value 

#do dictionary within dictionary
#get dictionary with f_id as key and f_id as value event_no and f_value so that you can see if the e_no is the same, then get

In [181]:
#test YOU CAN IGNORE THIS
dic = {'f17': {'e18': 'CT+'}, 'f18':{'e18': 'Uu'}}

In [182]:
#writing functions to execute above-mentioned steps YOU CAN IGNORE THIS
def get_int_ind(dic):
    """returns a list of dictionaries with integers as keys"""
    list_dic = []
    for key, value in dic.items():
        dic1 = {}
        #removing 'f' and tranforming number to an int so that later we can access the lowest integer
        key1 = int(key.strip('f'))
        dic1[key1] = value
        list_dic.append(dic1)
    return list_dic

In [183]:
list_dic = get_int_ind(dic)

In [184]:
#YOU CAN IGNORE THIS
def get_min_int(list_dic):
    """gets the the dictionary with the lowest integer as key"""
    list_k = []
    #value_list = []
    for item in list_dic:
        for k, v in item.items():
            list_k.append(k)
            x = min(float(s) for s in list_k)
        for k, v in item.items():
            if k == x:
                return item

In [185]:
#YOU CAN IGNORE THIS
value_list = get_min_int(list_dic)
print(value_list)

{17: {'e18': 'CT+'}}

In [186]:
#YOU CAN IGNORE THIS
test = 'f17'
test1 = int(test.strip('f'))
#print(type(test1))

def get_int_ind(dic):
    list_dic = []
    for key, value in dic.items():
        dic1 = {}
        key1 = int(key.strip('f'))
        dic1[key1] = value
        list_dic.append(dic1)
    return list_dic
    
print(list_dic)
list_k = []
for item in list_dic:
    for k, v in item.items():
        list_k.append(k)
        x = min(float(s) for s in list_k)
        
value_list = []
for item in list_dic:
    for k, v in item.items():
        if k == x:
            value_list.append(item)

print('wanted value', value_list)    
print('list', list_k)
print(x)

[{17: {'e18': 'CT+'}}, {18: {'e18': 'Uu'}}]
wanted value [{17: {'e18': 'CT+'}}]
list [17, 18]
17.0

In [187]:
#YOU CAN IGNORE THIS
#create a dictionary with f_id's as keys and event_no's as values 
#f_id's are unique so they work as keys, event-no's are not so they work as values
mydict_fid = modified_df.set_index('f_id')['event_no'].to_dict()
print(mydict_fid)

{'f1': 'e1', 'f2': 'e369', 'f3': 'e3', 'f4': 'e4', 'f5': 'e7', 'f6': 'e9', 'f7': 'e10', 'f8': 'e147', 'f9': 'e11', 'f10': 'e153', 'f11': 'e376', 'f12': 'e376', 'f13': 'e12', 'f14': 'e14', 'f15': 'e16', 'f16': 'e17', 'f17': 'e18', 'f18': 'e18', 'f19': 'e19', 'f20': 'e20', 'f21': 'e21', 'f22': 'e21', 'f23': 'e26', 'f24': 'e27', 'f25': 'e28', 'f26': 'e30', 'f27': 'e32', 'f28': 'e33', 'f29': 'e34', 'f30': 'e37', 'f31': 'e88', 'f32': 'e88', 'f33': 'e91', 'f34': 'e91', 'f35': 'e39', 'f36': 'e40', 'f37': 'e40', 'f38': 'e41', 'f39': 'e42', 'f40': 'e43', 'f41': 'e44', 'f42': 'e46', 'f43': 'e371', 'f44': 'e48', 'f45': 'e50', 'f46': 'e375', 'f47': 'e52', 'f48': 'e53', 'f49': 'e54', 'f50': 'e374', 'f51': 'e55', 'f52': 'e56', 'f53': 'e59', 'f54': 'e60', 'f55': 'e64', 'f56': 'e368', 'f57': 'e65', 'f58': 'e66', 'f59': 'e67'}

In [112]:
####This is the strategy I want to end up using
#in order to access the values, create dictionary with event_no's as keys and factuality values as values
#since event_no's are not unique, I used "groupby" to collect in a list the values corresponding to the same event_no
mydict_eventno = {k: g["f_value"].tolist() for k,g in modified_df.groupby("event_no")}
print(mydict_eventno)

{'e1': ['CT+'], 'e10': ['CT+'], 'e11': ['CT+'], 'e12': ['CT+'], 'e14': ['CT+'], 'e147': ['CT+'], 'e153': ['CT+'], 'e16': ['CT+'], 'e17': ['CT+'], 'e18': ['CT+', 'Uu'], 'e19': ['CT+'], 'e20': ['CT+'], 'e21': ['CT+', 'Uu'], 'e26': ['CT+'], 'e27': ['CT+'], 'e28': ['CT+'], 'e3': ['CT+'], 'e30': ['PR-'], 'e32': ['CT+'], 'e33': ['CT+'], 'e34': ['CT-'], 'e368': ['CT+'], 'e369': ['CT+'], 'e37': ['CT+'], 'e371': ['CT+'], 'e374': ['PR+'], 'e375': ['CT+'], 'e376': ['CT+', 'Uu'], 'e39': ['CT+'], 'e4': ['CT-'], 'e40': ['CT+', 'Uu'], 'e41': ['CT-'], 'e42': ['CT+'], 'e43': ['CT+'], 'e44': ['CT+'], 'e46': ['CT-'], 'e48': ['Uu'], 'e50': ['Uu'], 'e52': ['CT+'], 'e53': ['CT+'], 'e54': ['PS+'], 'e55': ['CT+'], 'e56': ['CT+'], 'e59': ['PR-'], 'e60': ['CT+'], 'e64': ['Uu'], 'e65': ['Uu'], 'e66': ['Uu'], 'e67': ['CT+'], 'e7': ['CT+'], 'e88': ['CT+', 'CT+'], 'e9': ['CT+'], 'e91': ['PR+', 'Uu']}

In [189]:
#note how the factuality value corresponding to the least embedded source is always the first in the list in the above dictionary
#here are the things I'm interested in: event_no's and the first f_value in the list
#event_no1 = #keys in mydict_eventno
#f_value = #[0] in value in mydict_eventno

In [208]:
###Now I would like to start building the final dataframe
#I use the dictionary mydict_eventno to build a dataframe
#Since we now have only one factuality value and one event_no per event
#the number of rows would not match with the number of rows contained in modified_df
#So I'm taking a different file which only contains events (no values upon which the duplication of the tokens and event_no's is based)
#Infile_events has the same # of rows as the two dataframes we obtained from the two dictionaries

In [204]:
#transform file with events into a dataframe
df_ev = pd.read_csv(infile_events, sep='\|', header=None).dropna(axis=1)

df_ev

/Users/benedettatorsi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

                             0   3       6        9               12
0   'ABC19980108.1830.0711.tml'  11   'e17'  'ei389'       'thought'
1   'ABC19980108.1830.0711.tml'  28  'e375'  'ei437'           'few'
2   'ABC19980108.1830.0711.tml'  30  'e374'  'ei436'        'gloomy'
3   'ABC19980108.1830.0711.tml'   8  'e376'  'ei438'    'invincible'
4   'ABC19980108.1830.0711.tml'  24  'e371'  'ei433'        'thirty'
5   'ABC19980108.1830.0711.tml'   3    'e7'  'ei379'        'fallen'
6   'ABC19980108.1830.0711.tml'  19   'e37'  'ei402'     'estimates'
7   'ABC19980108.1830.0711.tml'  11   'e18'  'ei390'          'deal'
8   'ABC19980108.1830.0711.tml'  18   'e34'  'ei401'          'find'
9   'ABC19980108.1830.0711.tml'  17   'e33'  'ei400'          'owns'
10  'ABC19980108.1830.0711.tml'  16   'e32'  'ei399'       'crashed'
11  'ABC19980108.1830.0711.tml'  15   'e30'  'ei398'         'break'
12  'ABC19980108.1830.0711.tml'   8   'e11'  'ei384'       'thought'
13  'ABC19980108.1830.0711.tml'   5   'e10'  'ei381'           'hit'
14  'ABC19980108.1830.0711.tml'  10   'e12'  'ei386'      'takeover'
15  'ABC19980108.1830.0711.tml'  10   'e14'  'ei387'          'news'
16  'ABC19980108.1830.0711.tml'  20   'e39'  'ei405'       'believe'
17  'ABC19980108.1830.0711.tml'  11   'e16'  'ei388'         'spent'
18  'ABC19980108.1830.0711.tml'  19   'e91'  'ei404'         'worth'
19  'ABC19980108.1830.0711.tml'  30   'e59'  'ei424'        'change'
20  'ABC19980108.1830.0711.tml'  30   'e55'  'ei420'         'think'
21  'ABC19980108.1830.0711.tml'   7  'e147'  'ei382'          'drop'
22  'ABC19980108.1830.0711.tml'  30   'e56'  'ei422'         'think'
23  'ABC19980108.1830.0711.tml'  25   'e50'  'ei415'     'discounts'
24  'ABC19980108.1830.0711.tml'  29   'e53'  'ei418'       'talking'
25  'ABC19980108.1830.0711.tml'  29   'e52'  'ei417'          'boom'
26  'ABC19980108.1830.0711.tml'  12   'e19'  'ei391'          'sold'
27  'ABC19980108.1830.0711.tml'  14   'e26'  'ei395'  'construction'
28  'ABC19980108.1830.0711.tml'  12   'e20'  'ei392'          'said'
29  'ABC19980108.1830.0711.tml'  21   'e41'  'ei407'       'believe'
30  'ABC19980108.1830.0711.tml'   4    'e9'  'ei380'          'lost'
31  'ABC19980108.1830.0711.tml'  29   'e54'  'ei419'       'layoffs'
32  'ABC19980108.1830.0711.tml'   2    'e4'  'ei378'       'helping'
33  'ABC19980108.1830.0711.tml'  32  'e368'  'ei430'     'recession'
34  'ABC19980108.1830.0711.tml'   1  'e369'  'ei431'           'bad'
35  'ABC19980108.1830.0711.tml'   1    'e1'  'ei375'       'turning'
36  'ABC19980108.1830.0711.tml'   2    'e3'  'ei377'    'assistance'
37  'ABC19980108.1830.0711.tml'  23   'e42'  'ei408'       'plunged'
38  'ABC19980108.1830.0711.tml'  23   'e43'  'ei409'        'soared'
39  'ABC19980108.1830.0711.tml'  20   'e40'  'ei406'         'going'
40  'ABC19980108.1830.0711.tml'  14   'e27'  'ei396'           'way'
41  'ABC19980108.1830.0711.tml'  23   'e46'  'ei412'      'spending'
42  'ABC19980108.1830.0711.tml'  12   'e21'  'ei393'        'double'
43  'ABC19980108.1830.0711.tml'  23   'e44'  'ei410'      'downturn'
44  'ABC19980108.1830.0711.tml'  25   'e48'  'ei414'           'get'
45  'ABC19980108.1830.0711.tml'  14   'e28'  'ei397'        'backed'
46  'ABC19980108.1830.0711.tml'  19   'e88'  'ei403'         'worth'
47  'ABC19980108.1830.0711.tml'  31   'e60'  'ei425'          'time'
48  'ABC19980108.1830.0711.tml'   8  'e153'  'ei383'      'problems'
49  'ABC19980108.1830.0711.tml'  31   'e64'  'ei426'    'reposition'
50  'ABC19980108.1830.0711.tml'  32   'e65'  'ei427'          'hold'
51  'ABC19980108.1830.0711.tml'  32   'e66'  'ei428'           'get'
52  'ABC19980108.1830.0711.tml'  32   'e67'  'ei429'          'goes'

In [205]:
df_ev.columns = ["article", 'id', "event_no", "ei_id",'token'] #Sets headings
df_ev["token"] = df_ev["token"].str.replace("'", "") #This removes the apostrophes so that the tokens can match
df_ev["event_no"] = df_ev["event_no"].str.replace("'", "") #This removes the apostrophes so that the tokens can match

In [206]:
modified_df_ev = df_ev.drop(['article','ei_id', 'id'], 1) #Drops unwanted columns

In [207]:
#53 rows
modified_df_ev

   event_no         token
0       e17       thought
1      e375           few
2      e374        gloomy
3      e376    invincible
4      e371        thirty
5        e7        fallen
6       e37     estimates
7       e18          deal
8       e34          find
9       e33          owns
10      e32       crashed
11      e30         break
12      e11       thought
13      e10           hit
14      e12      takeover
15      e14          news
16      e39       believe
17      e16         spent
18      e91         worth
19      e59        change
20      e55         think
21     e147          drop
22      e56         think
23      e50     discounts
24      e53       talking
25      e52          boom
26      e19          sold
27      e26  construction
28      e20          said
29      e41       believe
30       e9          lost
31      e54       layoffs
32       e4       helping
33     e368     recession
34     e369           bad
35       e1       turning
36       e3    assistance
37      e42       plunged
38      e43        soared
39      e40         going
40      e27           way
41      e46      spending
42      e21        double
43      e44      downturn
44      e48           get
45      e28        backed
46      e88         worth
47      e60          time
48     e153      problems
49      e64    reposition
50      e65          hold
51      e66           get
52      e67          goes

In [198]:
#create new dataframe with event_no's and f_values from dictionary
final_dict = {}
for k, v in mydict_eventno.items():
    final_dict[k] = v[0]

In [199]:
#checking number of rows
print(len(final_dict))

53

In [200]:
#transform final_dict into a dataframe
final_dataframe = pd.DataFrame(list(final_dict.items()),
                      columns=['event_no','f_value'])
print(len(final_dataframe))

53

In [209]:
#merge final_dataframe and modified_df_ev
merged_df3 = final_dataframe.merge(modified_df_ev, on=['event_no'], how='left') #Merges dataframes on 'event_no'
print(len(merged_df3))

53

In [212]:
#creating outfile
merged_df3.to_csv('events_values.csv')